version: '3'
services:
  maplestory:
    build: .
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306
    ports:
      - "7575-7577:7575-7577"
      - "8484:8484"

  db:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "heavenms"
      MYSQL_USER: "heavenms"
      MYSQL_PASSWORD: "heavenms"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:3306:3306"
